// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.27.0
// source: common.proto

package fivetran_sdk_v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TextField int32

const (
	TextField_PlainText TextField = 0
	TextField_Password  TextField = 1
	TextField_Hidden    TextField = 2
)

// Enum value maps for TextField.
var (
	TextField_name = map[int32]string{
		0: "PlainText",
		1: "Password",
		2: "Hidden",
	}
	TextField_value = map[string]int32{
		"PlainText": 0,
		"Password":  1,
		"Hidden":    2,
	}
)

func (x TextField) Enum() *TextField {
	p := new(TextField)
	*p = x
	return p
}

func (x TextField) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TextField) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (TextField) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x TextField) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TextField.Descriptor instead.
func (TextField) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

type DataType int32

const (
	DataType_UNSPECIFIED    DataType = 0
	DataType_BOOLEAN        DataType = 1
	DataType_SHORT          DataType = 2
	DataType_INT            DataType = 3
	DataType_LONG           DataType = 4
	DataType_DECIMAL        DataType = 5
	DataType_FLOAT          DataType = 6
	DataType_DOUBLE         DataType = 7
	DataType_NAIVE_DATE     DataType = 8
	DataType_NAIVE_DATETIME DataType = 9
	DataType_UTC_DATETIME   DataType = 10
	DataType_BINARY         DataType = 11
	DataType_XML            DataType = 12
	DataType_STRING         DataType = 13
	DataType_JSON           DataType = 14
	DataType_NAIVE_TIME     DataType = 15
)

// Enum value maps for DataType.
var (
	DataType_name = map[int32]string{
		0:  "UNSPECIFIED",
		1:  "BOOLEAN",
		2:  "SHORT",
		3:  "INT",
		4:  "LONG",
		5:  "DECIMAL",
		6:  "FLOAT",
		7:  "DOUBLE",
		8:  "NAIVE_DATE",
		9:  "NAIVE_DATETIME",
		10: "UTC_DATETIME",
		11: "BINARY",
		12: "XML",
		13: "STRING",
		14: "JSON",
		15: "NAIVE_TIME",
	}
	DataType_value = map[string]int32{
		"UNSPECIFIED":    0,
		"BOOLEAN":        1,
		"SHORT":          2,
		"INT":            3,
		"LONG":           4,
		"DECIMAL":        5,
		"FLOAT":          6,
		"DOUBLE":         7,
		"NAIVE_DATE":     8,
		"NAIVE_DATETIME": 9,
		"UTC_DATETIME":   10,
		"BINARY":         11,
		"XML":            12,
		"STRING":         13,
		"JSON":           14,
		"NAIVE_TIME":     15,
	}
)

func (x DataType) Enum() *DataType {
	p := new(DataType)
	*p = x
	return p
}

func (x DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[1].Descriptor()
}

func (DataType) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[1]
}

func (x DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataType.Descriptor instead.
func (DataType) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

type RecordType int32

const (
	RecordType_UPSERT   RecordType = 0
	RecordType_UPDATE   RecordType = 1
	RecordType_DELETE   RecordType = 2
	RecordType_TRUNCATE RecordType = 3
)

// Enum value maps for RecordType.
var (
	RecordType_name = map[int32]string{
		0: "UPSERT",
		1: "UPDATE",
		2: "DELETE",
		3: "TRUNCATE",
	}
	RecordType_value = map[string]int32{
		"UPSERT":   0,
		"UPDATE":   1,
		"DELETE":   2,
		"TRUNCATE": 3,
	}
)

func (x RecordType) Enum() *RecordType {
	p := new(RecordType)
	*p = x
	return p
}

func (x RecordType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecordType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[2].Descriptor()
}

func (RecordType) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[2]
}

func (x RecordType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RecordType.Descriptor instead.
func (RecordType) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

type ConfigurationFormRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigurationFormRequest) Reset() {
	*x = ConfigurationFormRequest{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationFormRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationFormRequest) ProtoMessage() {}

func (x *ConfigurationFormRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationFormRequest.ProtoReflect.Descriptor instead.
func (*ConfigurationFormRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

type ConfigurationFormResponse struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	SchemaSelectionSupported bool                   `protobuf:"varint,1,opt,name=schema_selection_supported,json=schemaSelectionSupported,proto3" json:"schema_selection_supported,omitempty"`
	TableSelectionSupported  bool                   `protobuf:"varint,2,opt,name=table_selection_supported,json=tableSelectionSupported,proto3" json:"table_selection_supported,omitempty"`
	Fields                   []*FormField           `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	Tests                    []*ConfigurationTest   `protobuf:"bytes,4,rep,name=tests,proto3" json:"tests,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ConfigurationFormResponse) Reset() {
	*x = ConfigurationFormResponse{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationFormResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationFormResponse) ProtoMessage() {}

func (x *ConfigurationFormResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationFormResponse.ProtoReflect.Descriptor instead.
func (*ConfigurationFormResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigurationFormResponse) GetSchemaSelectionSupported() bool {
	if x != nil {
		return x.SchemaSelectionSupported
	}
	return false
}

func (x *ConfigurationFormResponse) GetTableSelectionSupported() bool {
	if x != nil {
		return x.TableSelectionSupported
	}
	return false
}

func (x *ConfigurationFormResponse) GetFields() []*FormField {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *ConfigurationFormResponse) GetTests() []*ConfigurationTest {
	if x != nil {
		return x.Tests
	}
	return nil
}

type FormField struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Label       string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Required    *bool                  `protobuf:"varint,3,opt,name=required,proto3,oneof" json:"required,omitempty"`
	Description *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// Types that are valid to be assigned to Type:
	//
	//	*FormField_TextField
	//	*FormField_DropdownField
	//	*FormField_ToggleField
	//	*FormField_ConditionalFields
	//	*FormField_UploadField
	//	*FormField_DescriptiveDropdownFields
	Type          isFormField_Type `protobuf_oneof:"type"`
	DefaultValue  *string          `protobuf:"bytes,8,opt,name=default_value,json=defaultValue,proto3,oneof" json:"default_value,omitempty"`
	Placeholder   *string          `protobuf:"bytes,9,opt,name=placeholder,proto3,oneof" json:"placeholder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FormField) Reset() {
	*x = FormField{}
	mi := &file_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormField) ProtoMessage() {}

func (x *FormField) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormField.ProtoReflect.Descriptor instead.
func (*FormField) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *FormField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FormField) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *FormField) GetRequired() bool {
	if x != nil && x.Required != nil {
		return *x.Required
	}
	return false
}

func (x *FormField) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *FormField) GetType() isFormField_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *FormField) GetTextField() TextField {
	if x != nil {
		if x, ok := x.Type.(*FormField_TextField); ok {
			return x.TextField
		}
	}
	return TextField_PlainText
}

func (x *FormField) GetDropdownField() *DropdownField {
	if x != nil {
		if x, ok := x.Type.(*FormField_DropdownField); ok {
			return x.DropdownField
		}
	}
	return nil
}

func (x *FormField) GetToggleField() *ToggleField {
	if x != nil {
		if x, ok := x.Type.(*FormField_ToggleField); ok {
			return x.ToggleField
		}
	}
	return nil
}

func (x *FormField) GetConditionalFields() *ConditionalFields {
	if x != nil {
		if x, ok := x.Type.(*FormField_ConditionalFields); ok {
			return x.ConditionalFields
		}
	}
	return nil
}

func (x *FormField) GetUploadField() *UploadField {
	if x != nil {
		if x, ok := x.Type.(*FormField_UploadField); ok {
			return x.UploadField
		}
	}
	return nil
}

func (x *FormField) GetDescriptiveDropdownFields() *DescriptiveDropDownFields {
	if x != nil {
		if x, ok := x.Type.(*FormField_DescriptiveDropdownFields); ok {
			return x.DescriptiveDropdownFields
		}
	}
	return nil
}

func (x *FormField) GetDefaultValue() string {
	if x != nil && x.DefaultValue != nil {
		return *x.DefaultValue
	}
	return ""
}

func (x *FormField) GetPlaceholder() string {
	if x != nil && x.Placeholder != nil {
		return *x.Placeholder
	}
	return ""
}

type isFormField_Type interface {
	isFormField_Type()
}

type FormField_TextField struct {
	TextField TextField `protobuf:"varint,5,opt,name=text_field,json=textField,proto3,enum=fivetran_sdk.v2.TextField,oneof"`
}

type FormField_DropdownField struct {
	DropdownField *DropdownField `protobuf:"bytes,6,opt,name=dropdown_field,json=dropdownField,proto3,oneof"`
}

type FormField_ToggleField struct {
	ToggleField *ToggleField `protobuf:"bytes,7,opt,name=toggle_field,json=toggleField,proto3,oneof"`
}

type FormField_ConditionalFields struct {
	ConditionalFields *ConditionalFields `protobuf:"bytes,10,opt,name=conditional_fields,json=conditionalFields,proto3,oneof"`
}

type FormField_UploadField struct {
	UploadField *UploadField `protobuf:"bytes,11,opt,name=upload_field,json=uploadField,proto3,oneof"`
}

type FormField_DescriptiveDropdownFields struct {
	DescriptiveDropdownFields *DescriptiveDropDownFields `protobuf:"bytes,12,opt,name=descriptive_dropdown_fields,json=descriptiveDropdownFields,proto3,oneof"`
}

func (*FormField_TextField) isFormField_Type() {}

func (*FormField_DropdownField) isFormField_Type() {}

func (*FormField_ToggleField) isFormField_Type() {}

func (*FormField_ConditionalFields) isFormField_Type() {}

func (*FormField_UploadField) isFormField_Type() {}

func (*FormField_DescriptiveDropdownFields) isFormField_Type() {}

type UploadField struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AllowedFileType  []string               `protobuf:"bytes,1,rep,name=allowed_file_type,json=allowedFileType,proto3" json:"allowed_file_type,omitempty"`
	MaxFileSizeBytes int32                  `protobuf:"varint,2,opt,name=max_file_size_bytes,json=maxFileSizeBytes,proto3" json:"max_file_size_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UploadField) Reset() {
	*x = UploadField{}
	mi := &file_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadField) ProtoMessage() {}

func (x *UploadField) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadField.ProtoReflect.Descriptor instead.
func (*UploadField) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

func (x *UploadField) GetAllowedFileType() []string {
	if x != nil {
		return x.AllowedFileType
	}
	return nil
}

func (x *UploadField) GetMaxFileSizeBytes() int32 {
	if x != nil {
		return x.MaxFileSizeBytes
	}
	return 0
}

type DescriptiveDropDownFields struct {
	state                    protoimpl.MessageState      `protogen:"open.v1"`
	DescriptiveDropdownField []*DescriptiveDropDownField `protobuf:"bytes,1,rep,name=descriptive_dropdown_field,json=descriptiveDropdownField,proto3" json:"descriptive_dropdown_field,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *DescriptiveDropDownFields) Reset() {
	*x = DescriptiveDropDownFields{}
	mi := &file_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescriptiveDropDownFields) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescriptiveDropDownFields) ProtoMessage() {}

func (x *DescriptiveDropDownFields) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescriptiveDropDownFields.ProtoReflect.Descriptor instead.
func (*DescriptiveDropDownFields) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4}
}

func (x *DescriptiveDropDownFields) GetDescriptiveDropdownField() []*DescriptiveDropDownField {
	if x != nil {
		return x.DescriptiveDropdownField
	}
	return nil
}

type DescriptiveDropDownField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescriptiveDropDownField) Reset() {
	*x = DescriptiveDropDownField{}
	mi := &file_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescriptiveDropDownField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescriptiveDropDownField) ProtoMessage() {}

func (x *DescriptiveDropDownField) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescriptiveDropDownField.ProtoReflect.Descriptor instead.
func (*DescriptiveDropDownField) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{5}
}

func (x *DescriptiveDropDownField) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *DescriptiveDropDownField) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *DescriptiveDropDownField) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ConditionalFields struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Condition     *VisibilityCondition   `protobuf:"bytes,1,opt,name=condition,proto3" json:"condition,omitempty"`
	Fields        []*FormField           `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConditionalFields) Reset() {
	*x = ConditionalFields{}
	mi := &file_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConditionalFields) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConditionalFields) ProtoMessage() {}

func (x *ConditionalFields) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConditionalFields.ProtoReflect.Descriptor instead.
func (*ConditionalFields) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{6}
}

func (x *ConditionalFields) GetCondition() *VisibilityCondition {
	if x != nil {
		return x.Condition
	}
	return nil
}

func (x *ConditionalFields) GetFields() []*FormField {
	if x != nil {
		return x.Fields
	}
	return nil
}

type VisibilityCondition struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConditionField string                 `protobuf:"bytes,1,opt,name=condition_field,json=conditionField,proto3" json:"condition_field,omitempty"`
	// Types that are valid to be assigned to VisibleWhen:
	//
	//	*VisibilityCondition_BoolValue
	//	*VisibilityCondition_StringValue
	//	*VisibilityCondition_EmptyValue
	VisibleWhen   isVisibilityCondition_VisibleWhen `protobuf_oneof:"visible_when"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisibilityCondition) Reset() {
	*x = VisibilityCondition{}
	mi := &file_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisibilityCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisibilityCondition) ProtoMessage() {}

func (x *VisibilityCondition) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisibilityCondition.ProtoReflect.Descriptor instead.
func (*VisibilityCondition) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{7}
}

func (x *VisibilityCondition) GetConditionField() string {
	if x != nil {
		return x.ConditionField
	}
	return ""
}

func (x *VisibilityCondition) GetVisibleWhen() isVisibilityCondition_VisibleWhen {
	if x != nil {
		return x.VisibleWhen
	}
	return nil
}

func (x *VisibilityCondition) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.VisibleWhen.(*VisibilityCondition_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *VisibilityCondition) GetStringValue() string {
	if x != nil {
		if x, ok := x.VisibleWhen.(*VisibilityCondition_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *VisibilityCondition) GetEmptyValue() bool {
	if x != nil {
		if x, ok := x.VisibleWhen.(*VisibilityCondition_EmptyValue); ok {
			return x.EmptyValue
		}
	}
	return false
}

type isVisibilityCondition_VisibleWhen interface {
	isVisibilityCondition_VisibleWhen()
}

type VisibilityCondition_BoolValue struct {
	BoolValue bool `protobuf:"varint,2,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type VisibilityCondition_StringValue struct {
	StringValue string `protobuf:"bytes,3,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type VisibilityCondition_EmptyValue struct {
	EmptyValue bool `protobuf:"varint,4,opt,name=empty_value,json=emptyValue,proto3,oneof"`
}

func (*VisibilityCondition_BoolValue) isVisibilityCondition_VisibleWhen() {}

func (*VisibilityCondition_StringValue) isVisibilityCondition_VisibleWhen() {}

func (*VisibilityCondition_EmptyValue) isVisibilityCondition_VisibleWhen() {}

type DropdownField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DropdownField []string               `protobuf:"bytes,1,rep,name=dropdown_field,json=dropdownField,proto3" json:"dropdown_field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropdownField) Reset() {
	*x = DropdownField{}
	mi := &file_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropdownField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropdownField) ProtoMessage() {}

func (x *DropdownField) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropdownField.ProtoReflect.Descriptor instead.
func (*DropdownField) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{8}
}

func (x *DropdownField) GetDropdownField() []string {
	if x != nil {
		return x.DropdownField
	}
	return nil
}

type ToggleField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleField) Reset() {
	*x = ToggleField{}
	mi := &file_common_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleField) ProtoMessage() {}

func (x *ToggleField) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleField.ProtoReflect.Descriptor instead.
func (*ToggleField) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{9}
}

type ConfigurationTest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`   // unique identifier for the test
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"` // A few words indicating what we are testing, e.g. 'Connecting to database'
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigurationTest) Reset() {
	*x = ConfigurationTest{}
	mi := &file_common_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationTest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationTest) ProtoMessage() {}

func (x *ConfigurationTest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationTest.ProtoReflect.Descriptor instead.
func (*ConfigurationTest) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{10}
}

func (x *ConfigurationTest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConfigurationTest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type TestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Configuration map[string]string      `protobuf:"bytes,2,rep,name=configuration,proto3" json:"configuration,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestRequest) Reset() {
	*x = TestRequest{}
	mi := &file_common_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestRequest) ProtoMessage() {}

func (x *TestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestRequest.ProtoReflect.Descriptor instead.
func (*TestRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{11}
}

func (x *TestRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TestRequest) GetConfiguration() map[string]string {
	if x != nil {
		return x.Configuration
	}
	return nil
}

type TestResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*TestResponse_Success
	//	*TestResponse_Failure
	Response      isTestResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestResponse) Reset() {
	*x = TestResponse{}
	mi := &file_common_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestResponse) ProtoMessage() {}

func (x *TestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestResponse.ProtoReflect.Descriptor instead.
func (*TestResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{12}
}

func (x *TestResponse) GetResponse() isTestResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *TestResponse) GetSuccess() bool {
	if x != nil {
		if x, ok := x.Response.(*TestResponse_Success); ok {
			return x.Success
		}
	}
	return false
}

func (x *TestResponse) GetFailure() string {
	if x != nil {
		if x, ok := x.Response.(*TestResponse_Failure); ok {
			return x.Failure
		}
	}
	return ""
}

type isTestResponse_Response interface {
	isTestResponse_Response()
}

type TestResponse_Success struct {
	Success bool `protobuf:"varint,1,opt,name=success,proto3,oneof"`
}

type TestResponse_Failure struct {
	Failure string `protobuf:"bytes,2,opt,name=failure,proto3,oneof"`
}

func (*TestResponse_Success) isTestResponse_Response() {}

func (*TestResponse_Failure) isTestResponse_Response() {}

type SchemaList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schemas       []*Schema              `protobuf:"bytes,1,rep,name=schemas,proto3" json:"schemas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaList) Reset() {
	*x = SchemaList{}
	mi := &file_common_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaList) ProtoMessage() {}

func (x *SchemaList) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaList.ProtoReflect.Descriptor instead.
func (*SchemaList) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{13}
}

func (x *SchemaList) GetSchemas() []*Schema {
	if x != nil {
		return x.Schemas
	}
	return nil
}

type TableList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tables        []*Table               `protobuf:"bytes,1,rep,name=tables,proto3" json:"tables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableList) Reset() {
	*x = TableList{}
	mi := &file_common_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableList) ProtoMessage() {}

func (x *TableList) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableList.ProtoReflect.Descriptor instead.
func (*TableList) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{14}
}

func (x *TableList) GetTables() []*Table {
	if x != nil {
		return x.Tables
	}
	return nil
}

type Schema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Tables        []*Table               `protobuf:"bytes,2,rep,name=tables,proto3" json:"tables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema) Reset() {
	*x = Schema{}
	mi := &file_common_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema) ProtoMessage() {}

func (x *Schema) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema.ProtoReflect.Descriptor instead.
func (*Schema) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{15}
}

func (x *Schema) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Schema) GetTables() []*Table {
	if x != nil {
		return x.Tables
	}
	return nil
}

type DataTypeParams struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Params:
	//
	//	*DataTypeParams_Decimal
	//	*DataTypeParams_StringByteLength
	Params        isDataTypeParams_Params `protobuf_oneof:"params"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataTypeParams) Reset() {
	*x = DataTypeParams{}
	mi := &file_common_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataTypeParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataTypeParams) ProtoMessage() {}

func (x *DataTypeParams) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataTypeParams.ProtoReflect.Descriptor instead.
func (*DataTypeParams) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{16}
}

func (x *DataTypeParams) GetParams() isDataTypeParams_Params {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *DataTypeParams) GetDecimal() *DecimalParams {
	if x != nil {
		if x, ok := x.Params.(*DataTypeParams_Decimal); ok {
			return x.Decimal
		}
	}
	return nil
}

func (x *DataTypeParams) GetStringByteLength() int32 {
	if x != nil {
		if x, ok := x.Params.(*DataTypeParams_StringByteLength); ok {
			return x.StringByteLength
		}
	}
	return 0
}

type isDataTypeParams_Params interface {
	isDataTypeParams_Params()
}

type DataTypeParams_Decimal struct {
	Decimal *DecimalParams `protobuf:"bytes,1,opt,name=decimal,proto3,oneof"`
}

type DataTypeParams_StringByteLength struct {
	StringByteLength int32 `protobuf:"varint,2,opt,name=string_byte_length,json=stringByteLength,proto3,oneof"`
}

func (*DataTypeParams_Decimal) isDataTypeParams_Params() {}

func (*DataTypeParams_StringByteLength) isDataTypeParams_Params() {}

type DecimalParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Precision     uint32                 `protobuf:"varint,1,opt,name=precision,proto3" json:"precision,omitempty"`
	Scale         uint32                 `protobuf:"varint,2,opt,name=scale,proto3" json:"scale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecimalParams) Reset() {
	*x = DecimalParams{}
	mi := &file_common_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecimalParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecimalParams) ProtoMessage() {}

func (x *DecimalParams) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecimalParams.ProtoReflect.Descriptor instead.
func (*DecimalParams) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{17}
}

func (x *DecimalParams) GetPrecision() uint32 {
	if x != nil {
		return x.Precision
	}
	return 0
}

func (x *DecimalParams) GetScale() uint32 {
	if x != nil {
		return x.Scale
	}
	return 0
}

type ValueType struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Inner:
	//
	//	*ValueType_Null
	//	*ValueType_Bool
	//	*ValueType_Short
	//	*ValueType_Int
	//	*ValueType_Long
	//	*ValueType_Float
	//	*ValueType_Double
	//	*ValueType_NaiveDate
	//	*ValueType_NaiveDatetime
	//	*ValueType_UtcDatetime
	//	*ValueType_Decimal
	//	*ValueType_Binary
	//	*ValueType_String_
	//	*ValueType_Json
	//	*ValueType_Xml
	//	*ValueType_NaiveTime
	Inner         isValueType_Inner `protobuf_oneof:"inner"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueType) Reset() {
	*x = ValueType{}
	mi := &file_common_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueType) ProtoMessage() {}

func (x *ValueType) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueType.ProtoReflect.Descriptor instead.
func (*ValueType) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{18}
}

func (x *ValueType) GetInner() isValueType_Inner {
	if x != nil {
		return x.Inner
	}
	return nil
}

func (x *ValueType) GetNull() bool {
	if x != nil {
		if x, ok := x.Inner.(*ValueType_Null); ok {
			return x.Null
		}
	}
	return false
}

func (x *ValueType) GetBool() bool {
	if x != nil {
		if x, ok := x.Inner.(*ValueType_Bool); ok {
			return x.Bool
		}
	}
	return false
}

func (x *ValueType) GetShort() int32 {
	if x != nil {
		if x, ok := x.Inner.(*ValueType_Short); ok {
			return x.Short
		}
	}
	return 0
}

func (x *ValueType) GetInt() int32 {
	if x != nil {
		if x, ok := x.Inner.(*ValueType_Int); ok {
			return x.Int
		}
	}
	return 0
}

func (x *ValueType) GetLong() int64 {
	if x != nil {
		if x, ok := x.Inner.(*ValueType_Long); ok {
			return x.Long
		}
	}
	return 0
}

func (x *ValueType) GetFloat() float32 {
	if x != nil {
		if x, ok := x.Inner.(*ValueType_Float); ok {
			return x.Float
		}
	}
	return 0
}

func (x *ValueType) GetDouble() float64 {
	if x != nil {
		if x, ok := x.Inner.(*ValueType_Double); ok {
			return x.Double
		}
	}
	return 0
}

func (x *ValueType) GetNaiveDate() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.Inner.(*ValueType_NaiveDate); ok {
			return x.NaiveDate
		}
	}
	return nil
}

func (x *ValueType) GetNaiveDatetime() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.Inner.(*ValueType_NaiveDatetime); ok {
			return x.NaiveDatetime
		}
	}
	return nil
}

func (x *ValueType) GetUtcDatetime() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.Inner.(*ValueType_UtcDatetime); ok {
			return x.UtcDatetime
		}
	}
	return nil
}

func (x *ValueType) GetDecimal() string {
	if x != nil {
		if x, ok := x.Inner.(*ValueType_Decimal); ok {
			return x.Decimal
		}
	}
	return ""
}

func (x *ValueType) GetBinary() []byte {
	if x != nil {
		if x, ok := x.Inner.(*ValueType_Binary); ok {
			return x.Binary
		}
	}
	return nil
}

func (x *ValueType) GetString_() string {
	if x != nil {
		if x, ok := x.Inner.(*ValueType_String_); ok {
			return x.String_
		}
	}
	return ""
}

func (x *ValueType) GetJson() string {
	if x != nil {
		if x, ok := x.Inner.(*ValueType_Json); ok {
			return x.Json
		}
	}
	return ""
}

func (x *ValueType) GetXml() string {
	if x != nil {
		if x, ok := x.Inner.(*ValueType_Xml); ok {
			return x.Xml
		}
	}
	return ""
}

func (x *ValueType) GetNaiveTime() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.Inner.(*ValueType_NaiveTime); ok {
			return x.NaiveTime
		}
	}
	return nil
}

type isValueType_Inner interface {
	isValueType_Inner()
}

type ValueType_Null struct {
	Null bool `protobuf:"varint,1,opt,name=null,proto3,oneof"`
}

type ValueType_Bool struct {
	Bool bool `protobuf:"varint,2,opt,name=bool,proto3,oneof"`
}

type ValueType_Short struct {
	Short int32 `protobuf:"varint,3,opt,name=short,proto3,oneof"`
}

type ValueType_Int struct {
	Int int32 `protobuf:"varint,4,opt,name=int,proto3,oneof"`
}

type ValueType_Long struct {
	Long int64 `protobuf:"varint,5,opt,name=long,proto3,oneof"`
}

type ValueType_Float struct {
	Float float32 `protobuf:"fixed32,6,opt,name=float,proto3,oneof"`
}

type ValueType_Double struct {
	Double float64 `protobuf:"fixed64,7,opt,name=double,proto3,oneof"`
}

type ValueType_NaiveDate struct {
	NaiveDate *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=naive_date,json=naiveDate,proto3,oneof"`
}

type ValueType_NaiveDatetime struct {
	NaiveDatetime *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=naive_datetime,json=naiveDatetime,proto3,oneof"`
}

type ValueType_UtcDatetime struct {
	UtcDatetime *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=utc_datetime,json=utcDatetime,proto3,oneof"`
}

type ValueType_Decimal struct {
	Decimal string `protobuf:"bytes,11,opt,name=decimal,proto3,oneof"`
}

type ValueType_Binary struct {
	Binary []byte `protobuf:"bytes,12,opt,name=binary,proto3,oneof"`
}

type ValueType_String_ struct {
	String_ string `protobuf:"bytes,13,opt,name=string,proto3,oneof"`
}

type ValueType_Json struct {
	Json string `protobuf:"bytes,14,opt,name=json,proto3,oneof"`
}

type ValueType_Xml struct {
	Xml string `protobuf:"bytes,15,opt,name=xml,proto3,oneof"`
}

type ValueType_NaiveTime struct {
	NaiveTime *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=naive_time,json=naiveTime,proto3,oneof"`
}

func (*ValueType_Null) isValueType_Inner() {}

func (*ValueType_Bool) isValueType_Inner() {}

func (*ValueType_Short) isValueType_Inner() {}

func (*ValueType_Int) isValueType_Inner() {}

func (*ValueType_Long) isValueType_Inner() {}

func (*ValueType_Float) isValueType_Inner() {}

func (*ValueType_Double) isValueType_Inner() {}

func (*ValueType_NaiveDate) isValueType_Inner() {}

func (*ValueType_NaiveDatetime) isValueType_Inner() {}

func (*ValueType_UtcDatetime) isValueType_Inner() {}

func (*ValueType_Decimal) isValueType_Inner() {}

func (*ValueType_Binary) isValueType_Inner() {}

func (*ValueType_String_) isValueType_Inner() {}

func (*ValueType_Json) isValueType_Inner() {}

func (*ValueType_Xml) isValueType_Inner() {}

func (*ValueType_NaiveTime) isValueType_Inner() {}

type Table struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Columns       []*Column              `protobuf:"bytes,2,rep,name=columns,proto3" json:"columns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Table) Reset() {
	*x = Table{}
	mi := &file_common_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Table) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Table) ProtoMessage() {}

func (x *Table) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Table.ProtoReflect.Descriptor instead.
func (*Table) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{19}
}

func (x *Table) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Table) GetColumns() []*Column {
	if x != nil {
		return x.Columns
	}
	return nil
}

type Column struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          DataType               `protobuf:"varint,2,opt,name=type,proto3,enum=fivetran_sdk.v2.DataType" json:"type,omitempty"`
	PrimaryKey    bool                   `protobuf:"varint,3,opt,name=primary_key,json=primaryKey,proto3" json:"primary_key,omitempty"`
	Params        *DataTypeParams        `protobuf:"bytes,4,opt,name=params,proto3,oneof" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Column) Reset() {
	*x = Column{}
	mi := &file_common_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Column) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Column) ProtoMessage() {}

func (x *Column) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Column.ProtoReflect.Descriptor instead.
func (*Column) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{20}
}

func (x *Column) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Column) GetType() DataType {
	if x != nil {
		return x.Type
	}
	return DataType_UNSPECIFIED
}

func (x *Column) GetPrimaryKey() bool {
	if x != nil {
		return x.PrimaryKey
	}
	return false
}

func (x *Column) GetParams() *DataTypeParams {
	if x != nil {
		return x.Params
	}
	return nil
}

type Warning struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Warning) Reset() {
	*x = Warning{}
	mi := &file_common_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Warning) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Warning) ProtoMessage() {}

func (x *Warning) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Warning.ProtoReflect.Descriptor instead.
func (*Warning) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{21}
}

func (x *Warning) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_common_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{22}
}

func (x *Task) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\x0ffivetran_sdk.v2\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1a\n" +
	"\x18ConfigurationFormRequest\"\x83\x02\n" +
	"\x19ConfigurationFormResponse\x12<\n" +
	"\x1aschema_selection_supported\x18\x01 \x01(\bR\x18schemaSelectionSupported\x12:\n" +
	"\x19table_selection_supported\x18\x02 \x01(\bR\x17tableSelectionSupported\x122\n" +
	"\x06fields\x18\x03 \x03(\v2\x1a.fivetran_sdk.v2.FormFieldR\x06fields\x128\n" +
	"\x05tests\x18\x04 \x03(\v2\".fivetran_sdk.v2.ConfigurationTestR\x05tests\"\xe4\x05\n" +
	"\tFormField\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x1f\n" +
	"\brequired\x18\x03 \x01(\bH\x01R\brequired\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x02R\vdescription\x88\x01\x01\x12;\n" +
	"\n" +
	"text_field\x18\x05 \x01(\x0e2\x1a.fivetran_sdk.v2.TextFieldH\x00R\ttextField\x12G\n" +
	"\x0edropdown_field\x18\x06 \x01(\v2\x1e.fivetran_sdk.v2.DropdownFieldH\x00R\rdropdownField\x12A\n" +
	"\ftoggle_field\x18\a \x01(\v2\x1c.fivetran_sdk.v2.ToggleFieldH\x00R\vtoggleField\x12S\n" +
	"\x12conditional_fields\x18\n" +
	" \x01(\v2\".fivetran_sdk.v2.ConditionalFieldsH\x00R\x11conditionalFields\x12A\n" +
	"\fupload_field\x18\v \x01(\v2\x1c.fivetran_sdk.v2.UploadFieldH\x00R\vuploadField\x12l\n" +
	"\x1bdescriptive_dropdown_fields\x18\f \x01(\v2*.fivetran_sdk.v2.DescriptiveDropDownFieldsH\x00R\x19descriptiveDropdownFields\x12(\n" +
	"\rdefault_value\x18\b \x01(\tH\x03R\fdefaultValue\x88\x01\x01\x12%\n" +
	"\vplaceholder\x18\t \x01(\tH\x04R\vplaceholder\x88\x01\x01B\x06\n" +
	"\x04typeB\v\n" +
	"\t_requiredB\x0e\n" +
	"\f_descriptionB\x10\n" +
	"\x0e_default_valueB\x0e\n" +
	"\f_placeholder\"h\n" +
	"\vUploadField\x12*\n" +
	"\x11allowed_file_type\x18\x01 \x03(\tR\x0fallowedFileType\x12-\n" +
	"\x13max_file_size_bytes\x18\x02 \x01(\x05R\x10maxFileSizeBytes\"\x84\x01\n" +
	"\x19DescriptiveDropDownFields\x12g\n" +
	"\x1adescriptive_dropdown_field\x18\x01 \x03(\v2).fivetran_sdk.v2.DescriptiveDropDownFieldR\x18descriptiveDropdownField\"h\n" +
	"\x18DescriptiveDropDownField\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\x8b\x01\n" +
	"\x11ConditionalFields\x12B\n" +
	"\tcondition\x18\x01 \x01(\v2$.fivetran_sdk.v2.VisibilityConditionR\tcondition\x122\n" +
	"\x06fields\x18\x02 \x03(\v2\x1a.fivetran_sdk.v2.FormFieldR\x06fields\"\xb7\x01\n" +
	"\x13VisibilityCondition\x12'\n" +
	"\x0fcondition_field\x18\x01 \x01(\tR\x0econditionField\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x02 \x01(\bH\x00R\tboolValue\x12#\n" +
	"\fstring_value\x18\x03 \x01(\tH\x00R\vstringValue\x12!\n" +
	"\vempty_value\x18\x04 \x01(\bH\x00R\n" +
	"emptyValueB\x0e\n" +
	"\fvisible_when\"6\n" +
	"\rDropdownField\x12%\n" +
	"\x0edropdown_field\x18\x01 \x03(\tR\rdropdownField\"\r\n" +
	"\vToggleField\"=\n" +
	"\x11ConfigurationTest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\"\xba\x01\n" +
	"\vTestRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12U\n" +
	"\rconfiguration\x18\x02 \x03(\v2/.fivetran_sdk.v2.TestRequest.ConfigurationEntryR\rconfiguration\x1a@\n" +
	"\x12ConfigurationEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"R\n" +
	"\fTestResponse\x12\x1a\n" +
	"\asuccess\x18\x01 \x01(\bH\x00R\asuccess\x12\x1a\n" +
	"\afailure\x18\x02 \x01(\tH\x00R\afailureB\n" +
	"\n" +
	"\bresponse\"?\n" +
	"\n" +
	"SchemaList\x121\n" +
	"\aschemas\x18\x01 \x03(\v2\x17.fivetran_sdk.v2.SchemaR\aschemas\";\n" +
	"\tTableList\x12.\n" +
	"\x06tables\x18\x01 \x03(\v2\x16.fivetran_sdk.v2.TableR\x06tables\"L\n" +
	"\x06Schema\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12.\n" +
	"\x06tables\x18\x02 \x03(\v2\x16.fivetran_sdk.v2.TableR\x06tables\"\x86\x01\n" +
	"\x0eDataTypeParams\x12:\n" +
	"\adecimal\x18\x01 \x01(\v2\x1e.fivetran_sdk.v2.DecimalParamsH\x00R\adecimal\x12.\n" +
	"\x12string_byte_length\x18\x02 \x01(\x05H\x00R\x10stringByteLengthB\b\n" +
	"\x06params\"C\n" +
	"\rDecimalParams\x12\x1c\n" +
	"\tprecision\x18\x01 \x01(\rR\tprecision\x12\x14\n" +
	"\x05scale\x18\x02 \x01(\rR\x05scale\"\xae\x04\n" +
	"\tValueType\x12\x14\n" +
	"\x04null\x18\x01 \x01(\bH\x00R\x04null\x12\x14\n" +
	"\x04bool\x18\x02 \x01(\bH\x00R\x04bool\x12\x16\n" +
	"\x05short\x18\x03 \x01(\x05H\x00R\x05short\x12\x12\n" +
	"\x03int\x18\x04 \x01(\x05H\x00R\x03int\x12\x14\n" +
	"\x04long\x18\x05 \x01(\x03H\x00R\x04long\x12\x16\n" +
	"\x05float\x18\x06 \x01(\x02H\x00R\x05float\x12\x18\n" +
	"\x06double\x18\a \x01(\x01H\x00R\x06double\x12;\n" +
	"\n" +
	"naive_date\x18\b \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tnaiveDate\x12C\n" +
	"\x0enaive_datetime\x18\t \x01(\v2\x1a.google.protobuf.TimestampH\x00R\rnaiveDatetime\x12?\n" +
	"\futc_datetime\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampH\x00R\vutcDatetime\x12\x1a\n" +
	"\adecimal\x18\v \x01(\tH\x00R\adecimal\x12\x18\n" +
	"\x06binary\x18\f \x01(\fH\x00R\x06binary\x12\x18\n" +
	"\x06string\x18\r \x01(\tH\x00R\x06string\x12\x14\n" +
	"\x04json\x18\x0e \x01(\tH\x00R\x04json\x12\x12\n" +
	"\x03xml\x18\x0f \x01(\tH\x00R\x03xml\x12;\n" +
	"\n" +
	"naive_time\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tnaiveTimeB\a\n" +
	"\x05inner\"N\n" +
	"\x05Table\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x121\n" +
	"\acolumns\x18\x02 \x03(\v2\x17.fivetran_sdk.v2.ColumnR\acolumns\"\xb5\x01\n" +
	"\x06Column\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12-\n" +
	"\x04type\x18\x02 \x01(\x0e2\x19.fivetran_sdk.v2.DataTypeR\x04type\x12\x1f\n" +
	"\vprimary_key\x18\x03 \x01(\bR\n" +
	"primaryKey\x12<\n" +
	"\x06params\x18\x04 \x01(\v2\x1f.fivetran_sdk.v2.DataTypeParamsH\x00R\x06params\x88\x01\x01B\t\n" +
	"\a_params\"#\n" +
	"\aWarning\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\" \n" +
	"\x04Task\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage*4\n" +
	"\tTextField\x12\r\n" +
	"\tPlainText\x10\x00\x12\f\n" +
	"\bPassword\x10\x01\x12\n" +
	"\n" +
	"\x06Hidden\x10\x02*\xdb\x01\n" +
	"\bDataType\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\v\n" +
	"\aBOOLEAN\x10\x01\x12\t\n" +
	"\x05SHORT\x10\x02\x12\a\n" +
	"\x03INT\x10\x03\x12\b\n" +
	"\x04LONG\x10\x04\x12\v\n" +
	"\aDECIMAL\x10\x05\x12\t\n" +
	"\x05FLOAT\x10\x06\x12\n" +
	"\n" +
	"\x06DOUBLE\x10\a\x12\x0e\n" +
	"\n" +
	"NAIVE_DATE\x10\b\x12\x12\n" +
	"\x0eNAIVE_DATETIME\x10\t\x12\x10\n" +
	"\fUTC_DATETIME\x10\n" +
	"\x12\n" +
	"\n" +
	"\x06BINARY\x10\v\x12\a\n" +
	"\x03XML\x10\f\x12\n" +
	"\n" +
	"\x06STRING\x10\r\x12\b\n" +
	"\x04JSON\x10\x0e\x12\x0e\n" +
	"\n" +
	"NAIVE_TIME\x10\x0f*>\n" +
	"\n" +
	"RecordType\x12\n" +
	"\n" +
	"\x06UPSERT\x10\x00\x12\n" +
	"\n" +
	"\x06UPDATE\x10\x01\x12\n" +
	"\n" +
	"\x06DELETE\x10\x02\x12\f\n" +
	"\bTRUNCATE\x10\x03B\"H\x01P\x01Z\x1cfivetran.com/fivetran_sdk_v2b\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_common_proto_goTypes = []any{
	(TextField)(0),                    // 0: fivetran_sdk.v2.TextField
	(DataType)(0),                     // 1: fivetran_sdk.v2.DataType
	(RecordType)(0),                   // 2: fivetran_sdk.v2.RecordType
	(*ConfigurationFormRequest)(nil),  // 3: fivetran_sdk.v2.ConfigurationFormRequest
	(*ConfigurationFormResponse)(nil), // 4: fivetran_sdk.v2.ConfigurationFormResponse
	(*FormField)(nil),                 // 5: fivetran_sdk.v2.FormField
	(*UploadField)(nil),               // 6: fivetran_sdk.v2.UploadField
	(*DescriptiveDropDownFields)(nil), // 7: fivetran_sdk.v2.DescriptiveDropDownFields
	(*DescriptiveDropDownField)(nil),  // 8: fivetran_sdk.v2.DescriptiveDropDownField
	(*ConditionalFields)(nil),         // 9: fivetran_sdk.v2.ConditionalFields
	(*VisibilityCondition)(nil),       // 10: fivetran_sdk.v2.VisibilityCondition
	(*DropdownField)(nil),             // 11: fivetran_sdk.v2.DropdownField
	(*ToggleField)(nil),               // 12: fivetran_sdk.v2.ToggleField
	(*ConfigurationTest)(nil),         // 13: fivetran_sdk.v2.ConfigurationTest
	(*TestRequest)(nil),               // 14: fivetran_sdk.v2.TestRequest
	(*TestResponse)(nil),              // 15: fivetran_sdk.v2.TestResponse
	(*SchemaList)(nil),                // 16: fivetran_sdk.v2.SchemaList
	(*TableList)(nil),                 // 17: fivetran_sdk.v2.TableList
	(*Schema)(nil),                    // 18: fivetran_sdk.v2.Schema
	(*DataTypeParams)(nil),            // 19: fivetran_sdk.v2.DataTypeParams
	(*DecimalParams)(nil),             // 20: fivetran_sdk.v2.DecimalParams
	(*ValueType)(nil),                 // 21: fivetran_sdk.v2.ValueType
	(*Table)(nil),                     // 22: fivetran_sdk.v2.Table
	(*Column)(nil),                    // 23: fivetran_sdk.v2.Column
	(*Warning)(nil),                   // 24: fivetran_sdk.v2.Warning
	(*Task)(nil),                      // 25: fivetran_sdk.v2.Task
	nil,                               // 26: fivetran_sdk.v2.TestRequest.ConfigurationEntry
	(*timestamppb.Timestamp)(nil),     // 27: google.protobuf.Timestamp
}
var file_common_proto_depIdxs = []int32{
	5,  // 0: fivetran_sdk.v2.ConfigurationFormResponse.fields:type_name -> fivetran_sdk.v2.FormField
	13, // 1: fivetran_sdk.v2.ConfigurationFormResponse.tests:type_name -> fivetran_sdk.v2.ConfigurationTest
	0,  // 2: fivetran_sdk.v2.FormField.text_field:type_name -> fivetran_sdk.v2.TextField
	11, // 3: fivetran_sdk.v2.FormField.dropdown_field:type_name -> fivetran_sdk.v2.DropdownField
	12, // 4: fivetran_sdk.v2.FormField.toggle_field:type_name -> fivetran_sdk.v2.ToggleField
	9,  // 5: fivetran_sdk.v2.FormField.conditional_fields:type_name -> fivetran_sdk.v2.ConditionalFields
	6,  // 6: fivetran_sdk.v2.FormField.upload_field:type_name -> fivetran_sdk.v2.UploadField
	7,  // 7: fivetran_sdk.v2.FormField.descriptive_dropdown_fields:type_name -> fivetran_sdk.v2.DescriptiveDropDownFields
	8,  // 8: fivetran_sdk.v2.DescriptiveDropDownFields.descriptive_dropdown_field:type_name -> fivetran_sdk.v2.DescriptiveDropDownField
	10, // 9: fivetran_sdk.v2.ConditionalFields.condition:type_name -> fivetran_sdk.v2.VisibilityCondition
	5,  // 10: fivetran_sdk.v2.ConditionalFields.fields:type_name -> fivetran_sdk.v2.FormField
	26, // 11: fivetran_sdk.v2.TestRequest.configuration:type_name -> fivetran_sdk.v2.TestRequest.ConfigurationEntry
	18, // 12: fivetran_sdk.v2.SchemaList.schemas:type_name -> fivetran_sdk.v2.Schema
	22, // 13: fivetran_sdk.v2.TableList.tables:type_name -> fivetran_sdk.v2.Table
	22, // 14: fivetran_sdk.v2.Schema.tables:type_name -> fivetran_sdk.v2.Table
	20, // 15: fivetran_sdk.v2.DataTypeParams.decimal:type_name -> fivetran_sdk.v2.DecimalParams
	27, // 16: fivetran_sdk.v2.ValueType.naive_date:type_name -> google.protobuf.Timestamp
	27, // 17: fivetran_sdk.v2.ValueType.naive_datetime:type_name -> google.protobuf.Timestamp
	27, // 18: fivetran_sdk.v2.ValueType.utc_datetime:type_name -> google.protobuf.Timestamp
	27, // 19: fivetran_sdk.v2.ValueType.naive_time:type_name -> google.protobuf.Timestamp
	23, // 20: fivetran_sdk.v2.Table.columns:type_name -> fivetran_sdk.v2.Column
	1,  // 21: fivetran_sdk.v2.Column.type:type_name -> fivetran_sdk.v2.DataType
	19, // 22: fivetran_sdk.v2.Column.params:type_name -> fivetran_sdk.v2.DataTypeParams
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	file_common_proto_msgTypes[2].OneofWrappers = []any{
		(*FormField_TextField)(nil),
		(*FormField_DropdownField)(nil),
		(*FormField_ToggleField)(nil),
		(*FormField_ConditionalFields)(nil),
		(*FormField_UploadField)(nil),
		(*FormField_DescriptiveDropdownFields)(nil),
	}
	file_common_proto_msgTypes[7].OneofWrappers = []any{
		(*VisibilityCondition_BoolValue)(nil),
		(*VisibilityCondition_StringValue)(nil),
		(*VisibilityCondition_EmptyValue)(nil),
	}
	file_common_proto_msgTypes[12].OneofWrappers = []any{
		(*TestResponse_Success)(nil),
		(*TestResponse_Failure)(nil),
	}
	file_common_proto_msgTypes[16].OneofWrappers = []any{
		(*DataTypeParams_Decimal)(nil),
		(*DataTypeParams_StringByteLength)(nil),
	}
	file_common_proto_msgTypes[18].OneofWrappers = []any{
		(*ValueType_Null)(nil),
		(*ValueType_Bool)(nil),
		(*ValueType_Short)(nil),
		(*ValueType_Int)(nil),
		(*ValueType_Long)(nil),
		(*ValueType_Float)(nil),
		(*ValueType_Double)(nil),
		(*ValueType_NaiveDate)(nil),
		(*ValueType_NaiveDatetime)(nil),
		(*ValueType_UtcDatetime)(nil),
		(*ValueType_Decimal)(nil),
		(*ValueType_Binary)(nil),
		(*ValueType_String_)(nil),
		(*ValueType_Json)(nil),
		(*ValueType_Xml)(nil),
		(*ValueType_NaiveTime)(nil),
	}
	file_common_proto_msgTypes[20].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
