name: Test Destination Connector

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true

      - name: Set up protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.x'

      - name: Install protoc-gen-go and protoc-gen-go-grpc
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # To set up GAR_JSON_KEY:
      # 1. Go to Google Cloud Console (https://console.cloud.google.com)
      # 2. Navigate to IAM & Admin > Service Accounts
      # 3. Create a new service account or select an existing one
      # 4. Create a new JSON key for the service account
      # 5. In your GitHub repository, go to Settings > Secrets and variables > Actions
      # 6. Create a new secret named GAR_JSON_KEY
      # 7. Paste the entire contents of the JSON key file
      - name: Login to Google Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: us-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GAR_JSON_KEY }}

      - name: Run tests
        run: |
          # Create logs directory
          mkdir -p logs
          
          # Run the test script
          USE_DOCKER=true ./tests/destination-connector-test.sh
        env:
          SURREAL_FIVETRAN_DEBUG: "true"
          # These are optional - if not set, the script will use local SurrealDB
          # SURREALDB_ENDPOINT: ""
          # SURREALDB_TOKEN: ""
          # SURREALDB_NAMESPACE: ""
          # SURREALDB_DATABASE: ""

      - name: Upload test logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: logs/
          retention-days: 7
